### ISSUE TITLE
Changes to Scrollbar in the Landing Page. 

### ISSUE THREAD

**Issue by SarthakSKumar** [Akshata-Gunapache/CocaCola-Landing-Page#1]
I will design a nice looking scrollbar for the landing page 🤓😂

**Comment by Akshata-Gunapache** [comment]
@SarthakSKumar  Yes sure! Go ahead.

**Comment by hs-07** [comment]
@Akshata-Gunapache hey
it seems u havent assigned the issue to anyone,,,, assign me the issue ... i would love to work on your project

**Comment by Akshata-Gunapache** [comment]
@hs-07 I have assigned this issue to SarthakSKumar ....You can work on it if he is not able to .
